version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: todo_list
    container_name: db
    restart: always
    healthcheck:
      test: pg_isready -U test_user -d todo_list
      interval: 3s
      timeout: 3s
      retries: 3

  migrations:
    build: .
    container_name: migrations
    env_file:
      - .env
    command: >
      sh -c "./manage.py makemigrations && ./manage.py migrate"
    depends_on:
      db:
        condition: service_healthy

  api:
    build: .
    container_name: api
    env_file:
      - .env
    command: >
      sh -c "gunicorn -b 0.0.0.0:8000 todolist.wsgi"
    ports:
      - "8000:8000"
    depends_on:
      migrations:
        condition: service_completed_successfully

  front:
    image: sermalenk/skypro-front:lesson-35
    container_name: front
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
