version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 3s
      timeout: 3s
      retries: 3

  migrations:
    image: ${DOCKERHUB_USERNAME}/todolist_docker:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: migrations
    env_file:
      - .env
    command: >
      sh -c "./manage.py makemigrations && ./manage.py migrate"
    volumes:
      - .env:/todo_list_app/.env
    depends_on:
      db:
        condition: service_healthy

  api:
    image: ${DOCKERHUB_USERNAME}/todolist_docker:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    env_file:
      - .env
    command: >
      sh -c "./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .env:/todo_list_app/.env
    depends_on:
      migrations:
        condition: service_completed_successfully

  front:
    image: sermalenk/skypro-front:lesson-34
    container_name: front
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data:
