# Generated by Django 4.1.7 on 2023-04-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_goal_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='author',
            new_name='user',
        ),
    ]
