# Generated by Django 4.1.7 on 2023-04-30 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(verbose_name='Телеграм чат ID')),
                ('tg_user_id', models.IntegerField(verbose_name='Телеграм пользователь ID')),
                ('verification_code', models.CharField(max_length=10, verbose_name='Код верификации')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не подтвержден'), (2, 'Подтвержден')], default=1, verbose_name='Статус')),
                ('selected_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь приложения')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
