# Generated by Django 4.1.7 on 2023-04-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_status_alter_tguser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='selected_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не подтвержден'), (2, 'Подтвержден')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.IntegerField(verbose_name='Телеграм чат ID'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_user_id',
            field=models.IntegerField(verbose_name='Телеграм пользователь ID'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(max_length=10, verbose_name='Код верификации'),
        ),
    ]
