name: todo_list workflow
on: [push]
jobs:
  linter_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          exclude: "./core/migrations/"
          max-line-length: "120"
          ignore: F401
