name: todo_list workflow
on: [push]
jobs:
  linter_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          exclude: "./core/migrations/"
          max-line-length: "120"
          ignore: F401

  build_and_push_image:
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    runs-on: ubuntu-latest
    needs: linter_check
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todolist_docker:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: docker push
        run: docker push michaelrodionov/todolist_docker:$GITHUB_REF_NAME-$GITHUB_RUN_ID
